// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQ9IHNuhBRa5rNFd--cHGVfT7wHIfzSs',
    appId: '1:64615458679:web:7468c2f357b2c7a1f2a372',
    messagingSenderId: '64615458679',
    projectId: 'sellix-3f736',
    authDomain: 'sellix-3f736.firebaseapp.com',
    storageBucket: 'sellix-3f736.firebasestorage.app',
    measurementId: 'G-3ETXYPN4VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRU6RbB15Nx1HMT90QmHDImqZDuswqupk',
    appId: '1:64615458679:android:b2192fc45d56f50af2a372',
    messagingSenderId: '64615458679',
    projectId: 'sellix-3f736',
    storageBucket: 'sellix-3f736.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkynNrsotjPaXdKk8KaPsssglwMLbFtdc',
    appId: '1:64615458679:ios:1f91de7ab6530789f2a372',
    messagingSenderId: '64615458679',
    projectId: 'sellix-3f736',
    storageBucket: 'sellix-3f736.firebasestorage.app',
    iosBundleId: 'com.sellix.sellix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkynNrsotjPaXdKk8KaPsssglwMLbFtdc',
    appId: '1:64615458679:ios:1f91de7ab6530789f2a372',
    messagingSenderId: '64615458679',
    projectId: 'sellix-3f736',
    storageBucket: 'sellix-3f736.firebasestorage.app',
    iosBundleId: 'com.sellix.sellix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnQ9IHNuhBRa5rNFd--cHGVfT7wHIfzSs',
    appId: '1:64615458679:web:22158ba64000c270f2a372',
    messagingSenderId: '64615458679',
    projectId: 'sellix-3f736',
    authDomain: 'sellix-3f736.firebaseapp.com',
    storageBucket: 'sellix-3f736.firebasestorage.app',
    measurementId: 'G-92MRB46ZMX',
  );
}
